### PR TITLE
Updated API to work with new servers

### PR DESCRIPTION
**Pull request by ryanskidmore**

### CODE REVIEW

**Comment by wchill** [comment]
While I was successful with Fiddler in the past when figuring out some of the other API features, it doesn't seem to be working anymore on my Android device. All HTTPS connections die even with the certificates installed.

**Comment by wchill** [comment]
Ah, figured it out. For some reason Fiddler's HTTPS decryption is broken with Android 4.2.2, but works fine on 4.1.2.
Here's the raw dump:

```
POST https://feelinsonice.appspot.com/ph/send HTTP/1.1
User-Agent: Snapchat/4.0.20 (GT-N8013; Android 16; gzip)
Content-Length: 196
Content-Type: application/x-www-form-urlencoded
Host: feelinsonice.appspot.com
Connection: Keep-Alive

req_token=[REDACTED]&timestamp=1384081555689&media_id=[REDACTED]&time=3&username=[REDACTED]&recipient=[REDACTED]
```

It's also `ph/upload`.

**Comment by wchill** [comment]
Okay, after some testing, I found that the 500 error on `upload` was from some quirk with my multi-part POST implementation.

The 404 error probably resulted from the 500 error. Basically, nothing to see here; move along.

**Comment by salfa** [comment]
wchill, how did you solve your 500 error? I'm getting the same thing. I can't seem to figure it out..

**Comment by wchill** [comment]
It may be a bug in how you're handling/constructing your requests - I wrote a Java version of Snaphax with the Apache HTTPClient libraries, and updating those libraries caused my code to break because the new HTTPClient function calls constructed the requests differently

**Comment by salfa** [comment]
Take a look at my request.. (it's in objective c)

```
[request setValue:@"Snapchat/6.0.2 (iPhone; iOS 7.0.4; gzip)" forHTTPHeaderField:@"User-Agent"];

    [body appendData:[[NSString stringWithFormat:@"username=%@&",[curPictureData objectAtIndex: 3]]dataUsingEncoding:NSUTF8StringEncoding]];
    [body appendData:[[NSString stringWithFormat:@"timestamp=%@&",[curPictureData objectAtIndex:1]]dataUsingEncoding:NSUTF8StringEncoding]];
    [body appendData:[[NSString stringWithFormat:@"req_token=%@&",[curPictureData objectAtIndex:2]]dataUsingEncoding:NSUTF8StringEncoding]];
    [body appendData:[[NSString stringWithFormat:@"media_id=%@&",[curPictureData objectAtIndex:0]]dataUsingEncoding:NSUTF8StringEncoding]];
    [body appendData:[[NSString stringWithFormat:@"type=0&"]dataUsingEncoding:NSUTF8StringEncoding]];
    [body appendData:[[NSString stringWithFormat:@"data="]dataUsingEncoding:NSUTF8StringEncoding]];
    [body appendData:[NSData dataWithData:toEncrypt2]];
```

Just keep in mind the @"param=%@&". Are the names of the parameters correct? and the last one the data, I have it equalling the toEncrypt2, which is the encrypted picture.

Could it be a problem with the encryption? What is your encryption method in java?

Thanks for helping me through this. The logging in part works, just not upload and send.

**Pull request merged**
